name: Sentry Source Maps
run-name: ${{ github.actor }} merged to ${{ github.repository }} Sentry source maps upload...

# on:
#   push:
#     branches:
#       - main
#       - staging
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: echo "{data:[]}" >| src/data/tokens.json
      - run: cat src/data/tokens.json
      - run: npm i
      - run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - run: npm run sentry:sourcemaps
