name: Sentry Source Maps
run-name: ${{ github.actor }} merged to ${{ github.repository }} Sentry source maps upload...

on: [pull_request]
  # push:
  #   branches:
  #     - main
  #     - staging

jobs:
  sentry-sourcemaps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - run: npm run sentry:sourcemaps
